[package]
name = "rytmos-scribe"
version = "0.1.0"
edition = "2021"
description = "Generates Rytmos sheet music structs based on user input datastructures"

[dependencies]
rytmos-engrave = { path = "../rytmos-engrave" }
embedded-graphics = "0.8.1"
heapless = "0.8.0"
